
project_id = "sllihrbacnavuodegwxd"
[api]
enabled = true
[db]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[edge_functions]
enabled = true
[edge_functions.functions.payfast-webhook]
verify_jwt = false
