project_id = "sllihrbacnavuodegwxd"

[api]
enabled = true
url = "https://sllihrbacnavuodegwxd.supabase.co"

[functions.create-checkout]
verify_jwt = true

[functions.order-status-notification]
verify_jwt = true