
# This is the Supabase configuration file

project_id = "sllihrbacnavuodegwxd"

[api]
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = 50000000

[auth]
enable_signup = true

[functions]
[functions.payfast-webhook]
verify_jwt = false
