// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sllihrbacnavuodegwxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbGlocmJhY25hdnVvZGVnd3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwOTY0NjQsImV4cCI6MjA1MjY3MjQ2NH0.c2Q0nWs__tOx6ggxrm--fiBMwfkML_TtQLvcq2VUy3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);